package com.softdream.drunkersapp.ui.theme

import androidx.compose.ui.graphics.Color

// Generate them via theme builder
// https://material-foundation.github.io/material-theme-builder/#/custom

val drunkersAppLightPrimary = Color(0xFF825500)
val drunkersAppLightOnPrimary = Color(0xFFFFFFFF)
val drunkersAppLightPrimaryContainer = Color(0xFFFFDDAE)
val drunkersAppLightOnPrimaryContainer = Color(0xFF2A1800)
val drunkersAppLightSecondary = Color(0xFF6F5B40)
val drunkersAppLightOnSecondary = Color(0xFFFFFFFF)
val drunkersAppLightSecondaryContainer = Color(0xFFFADEBC)
val drunkersAppLightOnSecondaryContainer = Color(0xFF271904)
val drunkersAppLightTertiary = Color(0xFF516440)
val drunkersAppLightOnTertiary = Color(0xFFFFFFFF)
val drunkersAppLightTertiaryContainer = Color(0xFFD3EABC)
val drunkersAppLightOnTertiaryContainer = Color(0xFF102004)
val drunkersAppLightError = Color(0xFFBA1B1B)
val drunkersAppLightErrorContainer = Color(0xFFFFDAD4)
val drunkersAppLightOnError = Color(0xFFFFFFFF)
val drunkersAppLightOnErrorContainer = Color(0xFF410001)
val drunkersAppLightBackground = Color(0xFFFCFCFC)
val drunkersAppLightOnBackground = Color(0xFF1F1B16)
val drunkersAppLightSurface = Color(0xFFFCFCFC)
val drunkersAppLightOnSurface = Color(0xFF1F1B16)
val drunkersAppLightSurfaceVariant = Color(0xFFF0E0CF)
val drunkersAppLightOnSurfaceVariant = Color(0xFF4F4539)
val drunkersAppLightOutline = Color(0xFF817567)
val drunkersAppLightInverseOnSurface = Color(0xFFF9EFE6)
val drunkersAppLightInverseSurface = Color(0xFF34302A)
val drunkersAppLightPrimaryInverse = Color(0xFFFFB945)

val drunkersAppDarkPrimary = Color(0xFFFFB945)
val drunkersAppDarkOnPrimary = Color(0xFF452B00)
val drunkersAppDarkPrimaryContainer = Color(0xFF624000)
val drunkersAppDarkOnPrimaryContainer = Color(0xFFFFDDAE)
val drunkersAppDarkSecondary = Color(0xFFDDC3A2)
val drunkersAppDarkOnSecondary = Color(0xFF3E2E16)
val drunkersAppDarkSecondaryContainer = Color(0xFF56442B)
val drunkersAppDarkOnSecondaryContainer = Color(0xFFFADEBC)
val drunkersAppDarkTertiary = Color(0xFFB8CEA2)
val drunkersAppDarkOnTertiary = Color(0xFF243516)
val drunkersAppDarkTertiaryContainer = Color(0xFF3A4C2B)
val drunkersAppDarkOnTertiaryContainer = Color(0xFFD3EABC)
val drunkersAppDarkError = Color(0xFFFFB4A9)
val drunkersAppDarkErrorContainer = Color(0xFF930006)
val drunkersAppDarkOnError = Color(0xFF680003)
val drunkersAppDarkOnErrorContainer = Color(0xFFFFDAD4)
val drunkersAppDarkBackground = Color(0xFF1F1B16)
val drunkersAppDarkOnBackground = Color(0xFFEAE1D9)
val drunkersAppDarkSurface = Color(0xFF1F1B16)
val drunkersAppDarkOnSurface = Color(0xFFEAE1D9)
val drunkersAppDarkSurfaceVariant = Color(0xFF4F4539)
val drunkersAppDarkOnSurfaceVariant = Color(0xFFD3C4B4)
val drunkersAppDarkOutline = Color(0xFF9C8F80)
val drunkersAppDarkInverseOnSurface = Color(0xFF32281A)
val drunkersAppDarkInverseSurface = Color(0xFFEAE1D9)
val drunkersAppDarkPrimaryInverse = Color(0xFF624000)